CREATE TABLE REGISTERS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  SOCIAL_SECURITY_NUM VARCHAR(8),
  IDENTITY_NUMBER VARCHAR(8),
  PHONE_NUMBER VARCHAR(24)
);